import { EmoteItem } from "shared/types";

export interface EmoteConfig {
	ReactionDuration: number;
	ReactionCooldown: number;
	ReactionBillboardOffset: Vector3;
	ReactionMaxDistance: number;
	Dances: EmoteItem[];
	Poses: EmoteItem[];
	Reactions: EmoteItem[];
}

export const EMOTE_CONFIG: EmoteConfig = {
	ReactionDuration: 2.5,
	ReactionCooldown: 1.0,
	ReactionBillboardOffset: new Vector3(0, 3.2, 0),
	ReactionMaxDistance: 70,

	Dances: [
		{
			id: "afro_beat",
			name: "Afro Beat",
			category: "Dance",
			animationId: "rbxassetid://119082464915666",
			description: "Afro Beat",
		},
		{
			id: "afro_beat_2",
			name: "Afro Beat 2",
			category: "Dance",
			animationId: "rbxassetid://84395077255209",
			description: "Afro Beat 2",
		},
		{
			id: "aura_farming",
			name: "Aura Farming",
			category: "Dance",
			animationId: "rbxassetid://138415280000308",
			description: "Aura Farming",
		},
		{
			id: "beat_it",
			name: "Beat It",
			category: "Dance",
			animationId: "rbxassetid://117971351653031",
			description: "Beat It",
		},
		{
			id: "breakdance",
			name: "Breakdance",
			category: "Dance",
			animationId: "rbxassetid://94410649401519",
			description: "Breakdance",
		},
		{
			id: "club",
			name: "Club",
			category: "Dance",
			animationId: "rbxassetid://99791281219189",
			description: "Club",
		},
		{
			id: "club_2",
			name: "Club 2",
			category: "Dance",
			animationId: "rbxassetid://75350969455454",
			description: "Club 2",
		},
		{
			id: "club_3",
			name: "Club 3",
			category: "Dance",
			animationId: "rbxassetid://88305628346060",
			description: "Club 3",
		},
		{
			id: "cute",
			name: "Cute",
			category: "Dance",
			animationId: "rbxassetid://136211077148241",
			description: "Cute",
		},
		{
			id: "club_4",
			name: "Club 4",
			category: "Dance",
			animationId: "rbxassetid://131559500294792",
			description: "Club 4",
		},
		{
			id: "dawg",
			name: "Dawg",
			category: "Dance",
			animationId: "rbxassetid://132518492517951",
			description: "Dawg",
		},
		{
			id: "dj",
			name: "DJ",
			category: "Dance",
			animationId: "rbxassetid://122838088363560",
			description: "DJ",
		},
		{
			id: "drum",
			name: "Drum",
			category: "Dance",
			animationId: "rbxassetid://71961418473445",
			description: "Drum",
		},
		{
			id: "garnet",
			name: "Garnet",
			category: "Dance",
			animationId: "rbxassetid://98852748755167",
			description: "Garnet",
		},
		{
			id: "guitar",
			name: "Guitar",
			category: "Dance",
			animationId: "rbxassetid://86231853800188",
			description: "Guitar",
		},
		{
			id: "guitar_2",
			name: "Guitar 2",
			category: "Dance",
			animationId: "rbxassetid://87611876270730",
			description: "Guitar 2",
		},
		{
			id: "guitar_3",
			name: "Guitar 3",
			category: "Dance",
			animationId: "rbxassetid://85764998378014",
			description: "Guitar 3",
		},
		{
			id: "headbang",
			name: "Headbang",
			category: "Dance",
			animationId: "rbxassetid://115811243836422",
			description: "Headbang",
		},
		{
			id: "headbang_2",
			name: "Headbang 2",
			category: "Dance",
			animationId: "rbxassetid://87573617427753",
			description: "Headbang 2",
		},
		{
			id: "headbang_3",
			name: "Headbang 3",
			category: "Dance",
			animationId: "rbxassetid://71100151355042",
			description: "Headbang 3",
		},
		{
			id: "headbang_4",
			name: "Headbang 4",
			category: "Dance",
			animationId: "rbxassetid://70436976834407",
			description: "Headbang 4",
		},
		{
			id: "hip",
			name: "Hip",
			category: "Dance",
			animationId: "rbxassetid://103430166805929",
			description: "Hip",
		},
		{
			id: "hood",
			name: "Hood",
			category: "Dance",
			animationId: "rbxassetid://122854947549530",
			description: "Hood",
		},
		{
			id: "hood_2",
			name: "Hood 2",
			category: "Dance",
			animationId: "rbxassetid://82659107075605",
			description: "Hood 2",
		},
		{
			id: "jamal_groove",
			name: "Jamal Groove",
			category: "Dance",
			animationId: "rbxassetid://119774146582647",
			description: "Jamal Groove",
		},
		{
			id: "kicau_mania",
			name: "Kicau Mania",
			category: "Dance",
			animationId: "rbxassetid://133082075993432",
			description: "Kicau Mania",
		},
		{
			id: "mystical",
			name: "Mystical",
			category: "Dance",
			animationId: "rbxassetid://113998852158957",
			description: "Mystical",
		},
		{
			id: "pikiranku",
			name: "Pikiranku",
			category: "Dance",
			animationId: "rbxassetid://84218863081720",
			description: "Pikiranku",
		},
		{
			id: "psht",
			name: "PSHT",
			category: "Dance",
			animationId: "rbxassetid://102209336981399",
			description: "PSHT",
		},
		{
			id: "rakai",
			name: "Rakai",
			category: "Dance",
			animationId: "rbxassetid://113325039007208",
			description: "Rakai",
		},
		{
			id: "rat",
			name: "Rat",
			category: "Dance",
			animationId: "rbxassetid://122705537371584",
			description: "Rat",
		},
		{
			id: "reggae",
			name: "Reggae",
			category: "Dance",
			animationId: "rbxassetid://73516860500046",
			description: "Reggae",
		},
		{
			id: "shake_it",
			name: "Shake It",
			category: "Dance",
			animationId: "rbxassetid://131572749821994",
			description: "Shake It",
		},
		{
			id: "ska",
			name: "Ska",
			category: "Dance",
			animationId: "rbxassetid://112582598050091",
			description: "Ska",
		},
		{
			id: "stomp",
			name: "Stomp",
			category: "Dance",
			animationId: "rbxassetid://103594727473203",
			description: "Stomp",
		},
		{
			id: "sway",
			name: "Sway",
			category: "Dance",
			animationId: "rbxassetid://79306819945179",
			description: "Sway",
		},
		{
			id: "two_step",
			name: "Two Step",
			category: "Dance",
			animationId: "rbxassetid://76074206088570",
			description: "Two Step",
		},
		{
			id: "urban",
			name: "Urban",
			category: "Dance",
			animationId: "rbxassetid://89787425028432",
			description: "Urban",
		},
		{
			id: "vibe_flow",
			name: "Vibe Flow",
			category: "Dance",
			animationId: "rbxassetid://135974934723253",
			description: "Vibe Flow",
		},
		{
			id: "vibing_1",
			name: "Vibing 1",
			category: "Dance",
			animationId: "rbxassetid://72972447879639",
			description: "Vibing 1",
		},
		{
			id: "vibing_2",
			name: "Vibing 2",
			category: "Dance",
			animationId: "rbxassetid://125165259060596",
			description: "Vibing 2",
		},
		{
			id: "vibing_3",
			name: "Vibing 3",
			category: "Dance",
			animationId: "rbxassetid://101321160413423",
			description: "Vibing 3",
		},
		{
			id: "vibing_4",
			name: "Vibing 4",
			category: "Dance",
			animationId: "rbxassetid://71638269569438",
			description: "Vibing 4",
		},
		{
			id: "vibing_5",
			name: "Vibing 5",
			category: "Dance",
			animationId: "rbxassetid://87451990090218",
			description: "Vibing 5",
		},
	],

	Poses: [
		{
			id: "pose_bad_boy",
			name: "Bad Boy",
			category: "Pose",
			animationId: "rbxassetid://100524213290085",
			description: "Bad Boy pose",
		},
		{
			id: "pose_bad_girl",
			name: "Bad Girl",
			category: "Pose",
			animationId: "rbxassetid://94140662372825",
			description: "Bad Girl pose",
		},
		{
			id: "pose_buddha",
			name: "Buddha",
			category: "Pose",
			animationId: "rbxassetid://86494865690543",
			description: "Buddha pose",
		},
		{
			id: "pose_cheerful",
			name: "Cheerful",
			category: "Pose",
			animationId: "rbxassetid://93452746851044",
			description: "Cheerful pose",
		},
		{
			id: "pose_cool",
			name: "Cool",
			category: "Pose",
			animationId: "rbxassetid://76054457750091",
			description: "Cool pose",
		},
		{
			id: "pose_cute_lying",
			name: "Cute Lying",
			category: "Pose",
			animationId: "rbxassetid://83826555651864",
			description: "Cute Lying pose",
		},
		{
			id: "pose_cute_sit",
			name: "Cute Sit",
			category: "Pose",
			animationId: "rbxassetid://123139873230954",
			description: "Cute Sit pose",
		},
		{
			id: "pose_hand_stand",
			name: "Hand Stand",
			category: "Pose",
			animationId: "rbxassetid://110866341627749",
			description: "Hand Stand pose",
		},
		{
			id: "pose_heavy",
			name: "Heavy",
			category: "Pose",
			animationId: "rbxassetid://113408406952433",
			description: "Heavy pose",
		},
		{
			id: "pose_hug",
			name: "Hug",
			category: "Pose",
			animationId: "rbxassetid://108085414493917",
			description: "Hug pose",
		},
		{
			id: "pose_jackson",
			name: "Jackson",
			category: "Pose",
			animationId: "rbxassetid://121304645239006",
			description: "Jackson pose",
		},
		{
			id: "pose_karate",
			name: "Karate",
			category: "Pose",
			animationId: "rbxassetid://102167724500721",
			description: "Karate pose",
		},
		{
			id: "pose_kawaii",
			name: "Kawaii",
			category: "Pose",
			animationId: "rbxassetid://134779221937629",
			description: "Kawaii pose",
		},
		{
			id: "pose_lying",
			name: "Lying",
			category: "Pose",
			animationId: "rbxassetid://117124228770115",
			description: "Lying pose",
		},
		{
			id: "pose_needy_bounce",
			name: "Needy Bounce",
			category: "Pose",
			animationId: "rbxassetid://99206600349328",
			description: "Needy Bounce pose",
		},
		{
			id: "pose_sad",
			name: "Sad",
			category: "Pose",
			animationId: "rbxassetid://116588084933167",
			description: "Sad pose",
		},
		{
			id: "pose_sit_1",
			name: "Sit 1",
			category: "Pose",
			animationId: "rbxassetid://129069298051425",
			description: "Sitting pose 1",
		},
		{
			id: "pose_sit_2",
			name: "Sit 2",
			category: "Pose",
			animationId: "rbxassetid://96180643659743",
			description: "Sitting pose 2",
		},
		{
			id: "pose_sit_3",
			name: "Sit 3",
			category: "Pose",
			animationId: "rbxassetid://77714086840663",
			description: "Sitting pose 3",
		},
		{
			id: "pose_sit_4",
			name: "Sit 4",
			category: "Pose",
			animationId: "rbxassetid://130355781301070",
			description: "Sitting pose 4",
		},
		{
			id: "pose_sit_5",
			name: "Sit 5",
			category: "Pose",
			animationId: "rbxassetid://124634232157047",
			description: "Sitting pose 5",
		},
		{
			id: "pose_sit_embrace",
			name: "Sit Embrace",
			category: "Pose",
			animationId: "rbxassetid://112878863052596",
			description: "Sit Embrace pose",
		},
		{
			id: "pose_sleep",
			name: "Sleep",
			category: "Pose",
			animationId: "rbxassetid://120013122319938",
			description: "Sleep pose",
		},
		{
			id: "pose_sleep_2",
			name: "Sleep 2",
			category: "Pose",
			animationId: "rbxassetid://135277932223226",
			description: "Sleep 2 pose",
		},
		{
			id: "pose_spiderman",
			name: "Spiderman",
			category: "Pose",
			animationId: "rbxassetid://117615811966201",
			description: "Spiderman pose",
		},
		{
			id: "pose_tired",
			name: "Tired",
			category: "Pose",
			animationId: "rbxassetid://138938718796857",
			description: "Tired pose",
		},
		{
			id: "pose_wall_lean",
			name: "Wall Lean",
			category: "Pose",
			animationId: "rbxassetid://101702377972822",
			description: "Wall Lean pose",
		},
	],

	Reactions: [
		{ id: "react_angry", name: "Angry", category: "Reaction", icon: "😡" },
		{ id: "react_clap", name: "Clap", category: "Reaction", icon: "👏" },
		{ id: "react_question", name: "Confused", category: "Reaction", icon: "❓" },
		{ id: "react_cool", name: "Cool", category: "Reaction", icon: "😎" },
		{ id: "react_diamond", name: "Diamond", category: "Reaction", icon: "💎" },
		{ id: "react_fire", name: "Fire", category: "Reaction", icon: "🔥" },
		{ id: "react_laugh", name: "Laugh", category: "Reaction", icon: "😂" },
		{ id: "react_lightning", name: "Lightning", category: "Reaction", icon: "⚡" },
		{ id: "react_love", name: "Love", category: "Reaction", icon: "❤️" },
		{ id: "react_party", name: "Party", category: "Reaction", icon: "🎉" },
		{ id: "react_100", name: "Perfect", category: "Reaction", icon: "💯" },
		{ id: "react_pleading", name: "Pleading", category: "Reaction", icon: "🥺" },
		{ id: "react_skull", name: "Skull", category: "Reaction", icon: "💀" },
		{ id: "react_sleep", name: "Sleepy", category: "Reaction", icon: "💤" },
		{ id: "react_thumbsup", name: "Thumbs Up", category: "Reaction", icon: "👍" },
		{ id: "react_wave", name: "Wave", category: "Reaction", icon: "👋" },
	],
};
