import { EmoteItem } from "shared/types";

export interface EmoteConfig {
	ReactionDuration: number;
	ReactionCooldown: number;
	ReactionBillboardOffset: Vector3;
	ReactionMaxDistance: number;
	Dances: EmoteItem[];
	Poses: EmoteItem[];
	Reactions: EmoteItem[];
}

export const EMOTE_CONFIG: EmoteConfig = {
	ReactionDuration: 2.5,
	ReactionCooldown: 1.0,
	ReactionBillboardOffset: new Vector3(0, 3.2, 0),
	ReactionMaxDistance: 70,

	Dances: [
		{
			id: "air_guitar",
			name: "Air Guitar",
			category: "Dance",
			animationId: "rbxassetid://106866068448423",
			description: "Air Guitar",
		},
		{
			id: "air_guitar_2",
			name: "Air Guitar 2",
			category: "Dance",
			animationId: "rbxassetid://91421490966910",
			description: "Air Guitar 2",
		},
		{
			id: "air_guitar_3",
			name: "Air Guitar 3",
			category: "Dance",
			animationId: "rbxassetid://84277658889632",
			description: "Air Guitar 3",
		},
		{
			id: "air_guitar_4",
			name: "Air Guitar 4",
			category: "Dance",
			animationId: "rbxassetid://112455042185607",
			description: "Air Guitar 4",
		},
		{
			id: "aura_farming",
			name: "Aura Farming",
			category: "Dance",
			animationId: "rbxassetid://138193909712753",
			description: "Aura Farming",
		},
		{
			id: "belly_dance_2",
			name: "Belly Dance 2",
			category: "Dance",
			animationId: "rbxassetid://80495624917691",
			description: "Belly Dance 2",
		},
		{
			id: "blackpink",
			name: "Blackpink",
			category: "Dance",
			animationId: "rbxassetid://99544390369022",
			description: "Blackpink",
		},
		{
			id: "bounce",
			name: "Bounce",
			category: "Dance",
			animationId: "rbxassetid://91906601841332",
			description: "Bounce",
		},
		{
			id: "boxing",
			name: "Boxing",
			category: "Dance",
			animationId: "rbxassetid://90789727437128",
			description: "Boxing",
		},
		{
			id: "breakdance",
			name: "Breakdance",
			category: "Dance",
			animationId: "rbxassetid://113358406710986",
			description: "Breakdance",
		},
		{
			id: "breakdance_2",
			name: "Breakdance 2",
			category: "Dance",
			animationId: "rbxassetid://95250744550886",
			description: "Breakdance 2",
		},
		{
			id: "cheerleader",
			name: "Cheerleader",
			category: "Dance",
			animationId: "rbxassetid://71624905013267",
			description: "Cheerleader",
		},
		{
			id: "cute_lay",
			name: "Cute Lay",
			category: "Dance",
			animationId: "rbxassetid://123620658034206",
			description: "Cute Lay",
		},
		{
			id: "dolphin",
			name: "Dolphin",
			category: "Dance",
			animationId: "rbxassetid://131315611801138",
			description: "Dolphin",
		},
		{
			id: "drummer",
			name: "Drummer",
			category: "Dance",
			animationId: "rbxassetid://112936003228252",
			description: "Drummer",
		},
		{
			id: "drummer_2",
			name: "Drummer 2",
			category: "Dance",
			animationId: "rbxassetid://129617584166146",
			description: "Drummer 2",
		},
		{
			id: "drummer_3",
			name: "Drummer 3",
			category: "Dance",
			animationId: "rbxassetid://100424144048100",
			description: "Drummer 3",
		},
		{
			id: "folk_dance",
			name: "Folk Dance",
			category: "Dance",
			animationId: "rbxassetid://109368100709312",
			description: "Folk Dance",
		},
		{
			id: "guitar_headbang",
			name: "Guitar Headbang",
			category: "Dance",
			animationId: "rbxassetid://125494121590681",
			description: "Guitar Headbang",
		},
		{
			id: "headbang",
			name: "Headbang",
			category: "Dance",
			animationId: "rbxassetid://100417474137690",
			description: "Headbang",
		},
		{
			id: "jamal_dance",
			name: "Jamal Dance",
			category: "Dance",
			animationId: "rbxassetid://107372916399558",
			description: "Jamal Dance",
		},
		{
			id: "juice_wrld",
			name: "Juice WRLD",
			category: "Dance",
			animationId: "rbxassetid://100235898558878",
			description: "Juice WRLD",
		},
		{
			id: "kicau_mania",
			name: "Kicau Mania",
			category: "Dance",
			animationId: "rbxassetid://72622038243038",
			description: "Kicau Mania",
		},
		{
			id: "mashle",
			name: "Mashle",
			category: "Dance",
			animationId: "rbxassetid://99645065197555",
			description: "Mashle",
		},
		{
			id: "moskau",
			name: "Moskau",
			category: "Dance",
			animationId: "rbxassetid://81193862861420",
			description: "Moskau",
		},
		{
			id: "nyc_hood",
			name: "NYC Hood",
			category: "Dance",
			animationId: "rbxassetid://82739893263444",
			description: "NYC Hood",
		},
		{
			id: "party",
			name: "Party",
			category: "Dance",
			animationId: "rbxassetid://107811668806848",
			description: "Party",
		},
		{
			id: "penguin",
			name: "Penguin",
			category: "Dance",
			animationId: "rbxassetid://114188875136449",
			description: "Penguin",
		},
		{
			id: "pennywise",
			name: "Pennywise",
			category: "Dance",
			animationId: "rbxassetid://80876043958518",
			description: "Pennywise",
		},
		{
			id: "psht",
			name: "PSHT",
			category: "Dance",
			animationId: "rbxassetid://99080908538979",
			description: "PSHT",
		},
		{
			id: "pushup",
			name: "Pushup",
			category: "Dance",
			animationId: "rbxassetid://76009653563916",
			description: "Pushup",
		},
		{
			id: "rat_dance",
			name: "Rat Dance",
			category: "Dance",
			animationId: "rbxassetid://124639231932936",
			description: "Rat Dance",
		},
		{
			id: "reggae",
			name: "Reggae",
			category: "Dance",
			animationId: "rbxassetid://103827007868065",
			description: "Reggae",
		},
		{
			id: "reggae_2",
			name: "Reggae 2",
			category: "Dance",
			animationId: "rbxassetid://123230495725553",
			description: "Reggae 2",
		},
		{
			id: "shy",
			name: "Shy",
			category: "Dance",
			animationId: "rbxassetid://126901755893370",
			description: "Shy",
		},
		{
			id: "siuu",
			name: "Siuu",
			category: "Dance",
			animationId: "rbxassetid://111340913464143",
			description: "Siuu",
		},
		{
			id: "ska",
			name: "Ska",
			category: "Dance",
			animationId: "rbxassetid://123631260970769",
			description: "Ska",
		},
		{
			id: "spider",
			name: "Spider",
			category: "Dance",
			animationId: "rbxassetid://111292693161834",
			description: "Spider",
		},
		{
			id: "stretch",
			name: "Stretch",
			category: "Dance",
			animationId: "rbxassetid://71155304285259",
			description: "Stretch",
		},
		{
			id: "stroke",
			name: "Stroke",
			category: "Dance",
			animationId: "rbxassetid://126631858375815",
			description: "Stroke",
		},
		{
			id: "two_step",
			name: "Two Step",
			category: "Dance",
			animationId: "rbxassetid://108049545199205",
			description: "Two Step",
		},
		{
			id: "wiggle",
			name: "Wiggle",
			category: "Dance",
			animationId: "rbxassetid://131311087599486",
			description: "Wiggle",
		},
		{
			id: "wiggle_2",
			name: "Wiggle 2",
			category: "Dance",
			animationId: "rbxassetid://120619907255706",
			description: "Wiggle 2",
		},
	],

	Poses: [
		{
			id: "pose_crossed",
			name: "Crossed Arms",
			category: "Pose",
			animationId: "rbxassetid://182435998",
			description: "Melipat kedua tangan di dada",
		},
		{
			id: "pose_hero",
			name: "Hero Stand",
			category: "Pose",
			animationId: "rbxassetid://182436842",
			description: "Pose berdiri gagah ala pahlawan",
		},
		{
			id: "pose_chill",
			name: "Relaxed Chill",
			category: "Pose",
			animationId: "rbxassetid://182436935",
			description: "Sikap santai dan rileks",
		},
		{
			id: "pose_point",
			name: "Point Forward",
			category: "Pose",
			animationId: "rbxassetid://128853357",
			description: "Menunjuk ke arah depan",
		},
	],

	Reactions: [
		{ id: "react_laugh", name: "Tertawa", category: "Reaction", icon: "😂" },
		{ id: "react_fire", name: "Semangat", category: "Reaction", icon: "🔥" },
		{ id: "react_love", name: "Cinta", category: "Reaction", icon: "❤️" },
		{ id: "react_skull", name: "Mati Gaya", category: "Reaction", icon: "💀" },
		{ id: "react_cool", name: "Keren", category: "Reaction", icon: "😎" },
		{ id: "react_party", name: "Pesta", category: "Reaction", icon: "🎉" },
		{ id: "react_thumbsup", name: "Mantap", category: "Reaction", icon: "👍" },
		{ id: "react_pleading", name: "Tolong", category: "Reaction", icon: "🥺" },
		{ id: "react_angry", name: "Marah", category: "Reaction", icon: "😡" },
		{ id: "react_question", name: "Bingung", category: "Reaction", icon: "❓" },
		{ id: "react_lightning", name: "Petir", category: "Reaction", icon: "⚡" },
		{ id: "react_diamond", name: "Sultan", category: "Reaction", icon: "💎" },
		{ id: "react_sleep", name: "Ngantuk", category: "Reaction", icon: "💤" },
		{ id: "react_clap", name: "Tepuk Tangan", category: "Reaction", icon: "👏" },
		{ id: "react_wave", name: "Halo", category: "Reaction", icon: "👋" },
		{ id: "react_100", name: "Sempurna", category: "Reaction", icon: "💯" },
	],
};
