name: Discord Push Notification

on:
  push:
    branches: [ "main" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "@everyone"
          title: "Game Update & Patch Notes"
          noprefix: true
          nodetail: true
          color: 0x5865F2
          description: |
            ${{ github.event.head_commit.message }}

            —
            **Dev:** ${{ github.actor }}
          url: ${{ github.event.head_commit.url }}
